//
//  RouteService.swift
//  WePark
//
//  W8.5a — Mapbox Directions HTTP API wrapper for Drive Mode foundation.
//
//  Port map (PWA → Swift):
//    MAPBOX_DIRECTIONS_URL constant         → Self.directionsBaseURL    [index.html:5987]
//    fetchAndRenderRoute(fromLatLng)        → fetchRoute(from:to:alternatives:) [index.html:6252]
//    flattenSteps(route)                     → done at parse time         [index.html:6342]
//
//  Token sourcing:
//    Token is read from Bundle.main.object(forInfoDictionaryKey: "MAPBOX_ACCESS_TOKEN").
//    The Info.plist entry is generated by INFOPLIST_KEY_MAPBOX_ACCESS_TOKEN in
//    project.pbxproj, which interpolates $(MAPBOX_ACCESS_TOKEN) from
//    ios/WePark/Config.xcconfig (gitignored — see Config.xcconfig.example).
//    Never hardcode a token in source.
//
//  Networking is dependency-injected via URLSession so tests can swap a
//  URLProtocol mock. Default is URLSession.shared.
//

import Foundation
import CoreLocation

// MARK: - Errors

enum MapboxRouteError: Error, Equatable {
    /// Bundle.main does not contain a MAPBOX_ACCESS_TOKEN key, or it is empty.
    /// Indicates a misconfigured build (missing Config.xcconfig or pbxproj wiring).
    case missingToken

    /// URLSession failed before we got a response (DNS, offline, timeout).
    case network(message: String)

    /// HTTP response with a non-2xx status code.
    case http(status: Int)

    /// Response body was not valid JSON in the expected Mapbox shape.
    case decoding(message: String)

    /// Mapbox returned 200 with an empty `routes` array (e.g. coordinates not reachable).
    case noRoutes
}

// MARK: - Service

@MainActor
final class RouteService {
    /// Process-wide singleton. Construct your own instance with a custom
    /// `URLSession` in tests via the `URLProtocol` mock pattern.
    static let shared = RouteService()

    /// Mapbox Directions v5 driving profile.
    static let directionsBaseURL = "https://api.mapbox.com/directions/v5/mapbox/driving/"

    /// Info.plist key for the Mapbox public token.
    /// Populated from Config.xcconfig at build time.
    static let tokenInfoPlistKey = "MAPBOX_ACCESS_TOKEN"

    private let session: URLSession
    private let tokenProvider: () -> String?

    /// Designated initializer. Tests pass a `session` configured with
    /// `URLProtocol` mocks and override the `tokenProvider` to bypass Bundle.
    init(
        session: URLSession = .shared,
        tokenProvider: @escaping () -> String? = RouteService.bundleTokenProvider
    ) {
        self.session = session
        self.tokenProvider = tokenProvider
    }

    /// Default token source: read from `Bundle.main` Info.plist.
    static let bundleTokenProvider: () -> String? = {
        guard let raw = Bundle.main.object(forInfoDictionaryKey: tokenInfoPlistKey) as? String else {
            return nil
        }
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    // MARK: - Public API

    /// Fetch a driving route from Mapbox.
    ///
    /// - Parameters:
    ///   - from: Origin coordinate.
    ///   - to: Destination coordinate.
    ///   - alternatives: When true, request up to 3 alternative routes
    ///     (Mapbox `alternatives=true`). Required for parking-aware scoring
    ///     in W8.5b. When false, Mapbox returns a single best route.
    /// - Returns: Ordered `[DriveRoute]`. The Mapbox API returns the
    ///   "primary" route first; alternatives follow. Always contains at least
    ///   one element on success.
    /// - Throws: `MapboxRouteError` for any failure mode.
    func fetchRoute(
        from: CLLocationCoordinate2D,
        to: CLLocationCoordinate2D,
        alternatives: Bool = false
    ) async throws -> [DriveRoute] {
        guard let raw = tokenProvider() else {
            throw MapboxRouteError.missingToken
        }
        let token = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !token.isEmpty else {
            throw MapboxRouteError.missingToken
        }
        let url = try Self.buildURL(from: from, to: to, alternatives: alternatives, token: token)

        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(from: url)
        } catch {
            throw MapboxRouteError.network(message: error.localizedDescription)
        }

        if let http = response as? HTTPURLResponse, !(200..<300).contains(http.statusCode) {
            throw MapboxRouteError.http(status: http.statusCode)
        }

        let wire: MapboxDirectionsResponse
        do {
            wire = try JSONDecoder().decode(MapboxDirectionsResponse.self, from: data)
        } catch {
            throw MapboxRouteError.decoding(message: String(describing: error))
        }

        guard !wire.routes.isEmpty else {
            throw MapboxRouteError.noRoutes
        }

        return wire.routes.map { $0.toDomain() }
    }

    // MARK: - URL building

    /// Visible for testing.
    static func buildURL(
        from: CLLocationCoordinate2D,
        to: CLLocationCoordinate2D,
        alternatives: Bool,
        token: String
    ) throws -> URL {
        let coords = "\(from.longitude),\(from.latitude);\(to.longitude),\(to.latitude)"
        let base = directionsBaseURL + coords
        guard var components = URLComponents(string: base) else {
            throw MapboxRouteError.decoding(message: "invalid coordinates: \(coords)")
        }
        components.queryItems = [
            URLQueryItem(name: "access_token", value: token),
            URLQueryItem(name: "geometries", value: "geojson"),
            URLQueryItem(name: "steps", value: "true"),
            URLQueryItem(name: "overview", value: "full"),
            URLQueryItem(name: "alternatives", value: alternatives ? "true" : "false"),
        ]
        guard let url = components.url else {
            throw MapboxRouteError.decoding(message: "URLComponents.url returned nil")
        }
        return url
    }
}

// MARK: - Wire types (private to the service)

private struct MapboxDirectionsResponse: Decodable {
    let routes: [MapboxRoute]
}

private struct MapboxRoute: Decodable {
    let distance: Double
    let duration: Double
    let geometry: MapboxGeometry
    let legs: [MapboxLeg]

    func toDomain() -> DriveRoute {
        let flatSteps = legs.flatMap { $0.steps }.map { $0.toDomain() }
        return DriveRoute(
            distance: distance,
            duration: duration,
            geometry: geometry.toCoordinates(),
            steps: flatSteps
        )
    }
}

private struct MapboxGeometry: Decodable {
    /// GeoJSON LineString: array of `[lng, lat]` pairs.
    let coordinates: [[Double]]

    func toCoordinates() -> [CLLocationCoordinate2D] {
        coordinates.compactMap { pair in
            guard pair.count >= 2 else { return nil }
            return CLLocationCoordinate2D(latitude: pair[1], longitude: pair[0])
        }
    }
}

private struct MapboxLeg: Decodable {
    let steps: [MapboxStep]
}

private struct MapboxStep: Decodable {
    let distance: Double
    let duration: Double
    let geometry: MapboxGeometry
    let maneuver: MapboxManeuver

    func toDomain() -> DriveRouteStep {
        DriveRouteStep(
            distance: distance,
            duration: duration,
            maneuverLocation: maneuver.locationCoordinate,
            maneuverType: maneuver.type,
            maneuverModifier: maneuver.modifier,
            instruction: maneuver.instruction,
            geometry: geometry.toCoordinates()
        )
    }
}

private struct MapboxManeuver: Decodable {
    /// `[lng, lat]`.
    let location: [Double]
    let type: String
    let modifier: String?
    let instruction: String

    var locationCoordinate: CLLocationCoordinate2D {
        guard location.count >= 2 else {
            return CLLocationCoordinate2D(latitude: 0, longitude: 0)
        }
        return CLLocationCoordinate2D(latitude: location[1], longitude: location[0])
    }
}
