//
//  RouteService.swift
//  WePark
//
//  W8.5a — Mapbox Directions HTTP API wrapper for Drive Mode foundation.
//  W8.5c — M-2: Added RouteServicing protocol for dependency injection in tests and views.
//
//  Port map (PWA → Swift):
//    MAPBOX_DIRECTIONS_URL constant         → Self.directionsBaseURL    [index.html:5987]
//    fetchAndRenderRoute(fromLatLng)        → fetchRoute(from:to:alternatives:) [index.html:6252]
//    flattenSteps(route)                     → done at parse time         [index.html:6342]
//
//  Token sourcing:
//    Token is read from Bundle.main.object(forInfoDictionaryKey: "MAPBOX_ACCESS_TOKEN").
//    The Info.plist entry is generated by INFOPLIST_KEY_MAPBOX_ACCESS_TOKEN in
//    project.pbxproj, which interpolates $(MAPBOX_ACCESS_TOKEN) from
//    ios/WePark/Config.xcconfig (gitignored — see Config.xcconfig.example).
//    Never hardcode a token in source.
//
//  Networking is dependency-injected via URLSession so tests can swap a
//  URLProtocol mock. Default is URLSession.shared.
//

import Foundation
import CoreLocation

// MARK: - Errors

enum MapboxRouteError: Error, Equatable {
    /// Bundle.main does not contain a MAPBOX_ACCESS_TOKEN key, or it is empty.
    /// Indicates a misconfigured build (missing Config.xcconfig or pbxproj wiring).
    case missingToken

    /// URLSession failed before we got a response (DNS, offline, timeout).
    case network(message: String)

    /// HTTP response with a non-2xx status code.
    case http(status: Int)

    /// Response body was not valid JSON in the expected Mapbox shape.
    case decoding(message: String)

    /// Mapbox returned 200 with an empty `routes` array (e.g. coordinates not reachable).
    case noRoutes
}

// MARK: - RouteServicing protocol (M-2)

/// Protocol seam for route fetching — enables mock injection in tests and views.
/// `RouteService` conforms. `DriveModeDestinationView` is typed against this protocol.
///
/// M-2 carry-over from W8.5b QA: `pickBestParkingAwareRoute` was originally a `static`
/// method on the concrete class. Swift protocols don't support static method requirements
/// cleanly with `@MainActor`. Recommendation from tech-lead (W8.5c spec §4 step 2):
/// make it an instance method on the protocol; the conforming class can still call the
/// static implementation internally.
@MainActor
protocol RouteServicing: AnyObject {
    /// Fetch a driving route from the underlying directions service.
    func fetchRoute(
        from: CLLocationCoordinate2D,
        to: CLLocationCoordinate2D,
        alternatives: Bool
    ) async throws -> [DriveRoute]

    /// Select the best parking-aware route from a set of alternatives.
    /// Instance method (vs. static) so it can be a protocol requirement on `@MainActor`.
    func pickBestParkingAwareRoute(
        _ routes: [DriveRoute],
        segments: [Segment],
        engine: ParkingRulesEngine,
        now: Date
    ) -> DriveRoute?
}

// MARK: - Service

@MainActor
final class RouteService: RouteServicing {
    /// Process-wide singleton. Construct your own instance with a custom
    /// `URLSession` in tests via the `URLProtocol` mock pattern.
    static let shared = RouteService()

    /// Mapbox Directions v5 driving profile.
    static let directionsBaseURL = "https://api.mapbox.com/directions/v5/mapbox/driving/"

    /// Info.plist key for the Mapbox public token.
    /// Populated from Config.xcconfig at build time.
    static let tokenInfoPlistKey = "MAPBOX_ACCESS_TOKEN"

    private let session: URLSession
    private let tokenProvider: () -> String?

    /// Designated initializer. Tests pass a `session` configured with
    /// `URLProtocol` mocks and override the `tokenProvider` to bypass Bundle.
    init(
        session: URLSession = .shared,
        tokenProvider: @escaping () -> String? = RouteService.bundleTokenProvider
    ) {
        self.session = session
        self.tokenProvider = tokenProvider
    }

    /// Default token source: read from `Bundle.main` Info.plist.
    static let bundleTokenProvider: () -> String? = {
        guard let raw = Bundle.main.object(forInfoDictionaryKey: tokenInfoPlistKey) as? String else {
            return nil
        }
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    // MARK: - Public API

    /// Fetch a driving route from Mapbox.
    ///
    /// - Parameters:
    ///   - from: Origin coordinate.
    ///   - to: Destination coordinate.
    ///   - alternatives: When true, request up to 3 alternative routes
    ///     (Mapbox `alternatives=true`). Required for parking-aware scoring
    ///     in W8.5b. When false, Mapbox returns a single best route.
    /// - Returns: Ordered `[DriveRoute]`. The Mapbox API returns the
    ///   "primary" route first; alternatives follow. Always contains at least
    ///   one element on success.
    /// - Throws: `MapboxRouteError` for any failure mode.
    func fetchRoute(
        from: CLLocationCoordinate2D,
        to: CLLocationCoordinate2D,
        alternatives: Bool = false
    ) async throws -> [DriveRoute] {
        guard let raw = tokenProvider() else {
            throw MapboxRouteError.missingToken
        }
        let token = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !token.isEmpty else {
            throw MapboxRouteError.missingToken
        }
        let url = try Self.buildURL(from: from, to: to, alternatives: alternatives, token: token)

        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(from: url)
        } catch {
            throw MapboxRouteError.network(message: error.localizedDescription)
        }

        if let http = response as? HTTPURLResponse, !(200..<300).contains(http.statusCode) {
            throw MapboxRouteError.http(status: http.statusCode)
        }

        let wire: MapboxDirectionsResponse
        do {
            wire = try JSONDecoder().decode(MapboxDirectionsResponse.self, from: data)
        } catch {
            throw MapboxRouteError.decoding(message: String(describing: error))
        }

        guard !wire.routes.isEmpty else {
            throw MapboxRouteError.noRoutes
        }

        return wire.routes.map { $0.toDomain() }
    }

    /// Instance method conforming to `RouteServicing`. Delegates to the static implementation.
    func pickBestParkingAwareRoute(
        _ routes: [DriveRoute],
        segments: [Segment],
        engine: ParkingRulesEngine,
        now: Date = .nowET
    ) -> DriveRoute? {
        RouteService.pickBestParkingAwareRoute(routes, segments: segments, engine: engine, now: now)
    }

    // MARK: - URL building

    /// Visible for testing.
    static func buildURL(
        from: CLLocationCoordinate2D,
        to: CLLocationCoordinate2D,
        alternatives: Bool,
        token: String
    ) throws -> URL {
        let coords = "\(from.longitude),\(from.latitude);\(to.longitude),\(to.latitude)"
        let base = directionsBaseURL + coords
        guard var components = URLComponents(string: base) else {
            throw MapboxRouteError.decoding(message: "invalid coordinates: \(coords)")
        }
        components.queryItems = [
            URLQueryItem(name: "access_token", value: token),
            URLQueryItem(name: "geometries", value: "geojson"),
            URLQueryItem(name: "steps", value: "true"),
            URLQueryItem(name: "overview", value: "full"),
            URLQueryItem(name: "alternatives", value: alternatives ? "true" : "false"),
        ]
        guard let url = components.url else {
            throw MapboxRouteError.decoding(message: "URLComponents.url returned nil")
        }
        return url
    }
}

// MARK: - W8.5b: Parking-aware route scoring

extension RouteService {

    /// Port of `pickBestParkingAwareRoute` from `index.html:6298–6340`.
    ///
    /// Scores each candidate route by counting free/metered block faces within ~30m
    /// of the route geometry, then subtracts a duration penalty. The highest-scoring
    /// route wins; ties fall back to the primary route (`routes[0]`).
    ///
    /// - Parameters:
    ///   - routes: The ordered `[DriveRoute]` from `fetchRoute(alternatives:true)`.
    ///     Mapbox returns the primary route first.
    ///   - segments: The currently-loaded tile segments from `TileLoader`.
    ///   - engine: The `ParkingRulesEngine` instance for safety-label evaluation.
    ///   - now: Evaluation timestamp. Defaults to the current Eastern Time.
    /// - Returns: The best-scoring `DriveRoute`, or `nil` if `routes` is empty.
    static func pickBestParkingAwareRoute(
        _ routes: [DriveRoute],
        segments: [Segment],
        engine: ParkingRulesEngine,
        now: Date = .nowET
    ) -> DriveRoute? {
        guard !routes.isEmpty else { return nil }
        guard routes.count > 1 else { return routes[0] }

        // Categories to skip — these are not parkable faces.
        // PWA skip set: NO_STANDING, NO_PARKING, SPECIAL, TRUCK_LOADING, UNKNOWN.
        let skipCategories: Set<Category> = [.noStanding, .noParking, .special, .truckLoading, .unknown]

        var best: DriveRoute = routes[0]
        var bestScore: Double = -.infinity

        for route in routes {
            var score: Double = 0

            let coords = route.geometry
            guard !coords.isEmpty else { continue }

            // Sample ~60 points from the route geometry — same stride formula as PWA.
            // PWA: Math.max(1, Math.floor(coords.length / 60))
            let sampleStride = max(1, coords.count / 60)
            let samplePoints: [CLLocationCoordinate2D] = Swift.stride(from: 0, to: coords.count, by: sampleStride).map { coords[$0] }

            // Block deduplication: same logic as PWA blockKey = street|from|to.
            var counted = Set<String>()

            for seg in segments {
                guard seg.line.count >= 2 else { continue }

                // Determine dominant category — skip non-parkable faces.
                let dom = seg.dominantCategory ?? .unknown
                if skipCategories.contains(dom) { continue }

                // Segment midpoint — line is [lat, lng] per HANDOFF W2.
                let midIndex = seg.line.count / 2
                let midPair = seg.line[midIndex]
                guard midPair.count >= 2 else { continue }
                let segMidLat = midPair[0]
                let segMidLng = midPair[1]
                let segMidLocation = CLLocation(latitude: segMidLat, longitude: segMidLng)

                // Check if any sample point is within 30m of the segment midpoint.
                var nearAny = false
                for sp in samplePoints {
                    let sampleLocation = CLLocation(latitude: sp.latitude, longitude: sp.longitude)
                    if sampleLocation.distance(from: segMidLocation) <= 30.0 {
                        nearAny = true
                        break
                    }
                }
                guard nearAny else { continue }

                // Block dedup — same key as PWA and ContentView.findCandidateSegments.
                let blockKey = "\(seg.street)|\(seg.fromStreet)|\(seg.to)"
                guard !counted.contains(blockKey) else { continue }
                counted.insert(blockKey)

                // Score: free → +3, metered → +1.
                // Use safetyLabel (which handles ASP suspension) for correctness,
                // mirroring the PWA's `actionableSafetyLabel(seg).severity` check.
                let label = engine.safetyLabel(for: seg, at: now)
                switch label.severity {
                case .free:
                    score += 3
                case .metered:
                    score += 1
                case .restricted, .unknown:
                    break
                case .comingSoon:
                    // TF2-18: unreachable in practice — `ParkingRulesEngine.safetyLabel(for:at:)`
                    // (called above) still only ever returns free/metered/restricted/unknown;
                    // `.comingSoon` is produced exclusively by
                    // `DrivingContextService.aggregateSideDetail`'s side-aggregation layer,
                    // which this route-scoring code never touches. Branch exists only because
                    // `SafetyLabel.Severity` gained a case and Swift requires exhaustiveness.
                    break
                }
            }

            // Duration penalty: 1 point per 600 seconds (10-minute unit), same as PWA.
            score -= route.duration / 600.0

            if score > bestScore {
                bestScore = score
                best = route
            }
        }

        return best
    }
}

// MARK: - Wire types (private to the service)

private struct MapboxDirectionsResponse: Decodable {
    let routes: [MapboxRoute]
}

private struct MapboxRoute: Decodable {
    let distance: Double
    let duration: Double
    let geometry: MapboxGeometry
    let legs: [MapboxLeg]

    func toDomain() -> DriveRoute {
        let flatSteps = legs.flatMap { $0.steps }.map { $0.toDomain() }
        return DriveRoute(
            distance: distance,
            duration: duration,
            geometry: geometry.toCoordinates(),
            steps: flatSteps
        )
    }
}

private struct MapboxGeometry: Decodable {
    /// GeoJSON LineString: array of `[lng, lat]` pairs.
    let coordinates: [[Double]]

    func toCoordinates() -> [CLLocationCoordinate2D] {
        coordinates.compactMap { pair in
            guard pair.count >= 2 else { return nil }
            return CLLocationCoordinate2D(latitude: pair[1], longitude: pair[0])
        }
    }
}

private struct MapboxLeg: Decodable {
    let steps: [MapboxStep]
}

private struct MapboxStep: Decodable {
    let distance: Double
    let duration: Double
    let geometry: MapboxGeometry
    let maneuver: MapboxManeuver

    func toDomain() -> DriveRouteStep {
        DriveRouteStep(
            distance: distance,
            duration: duration,
            maneuverLocation: maneuver.locationCoordinate,
            maneuverType: maneuver.type,
            maneuverModifier: maneuver.modifier,
            instruction: maneuver.instruction,
            geometry: geometry.toCoordinates()
        )
    }
}

private struct MapboxManeuver: Decodable {
    /// `[lng, lat]`.
    let location: [Double]
    let type: String
    let modifier: String?
    let instruction: String

    var locationCoordinate: CLLocationCoordinate2D {
        guard location.count >= 2 else {
            return CLLocationCoordinate2D(latitude: 0, longitude: 0)
        }
        return CLLocationCoordinate2D(latitude: location[1], longitude: location[0])
    }
}
